In [2]:
import numpy as np

In [ ]:
# 1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [9]:
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# 2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [12]:
a = np.zeros((3, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [17]:
a = np.random.randint(1,11, size=(5,5))
print(a)

[[ 4 10  1  4  5]
 [ 9  8 10  1  1]
 [ 9  6  8  6  6]
 [ 7  7  1  5  1]
 [10  3  9  3  4]]


In [ ]:
# 4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [20]:
a = np.random.random((4,4))
print(a)

[[0.81406808 0.73074942 0.37437165 0.981322  ]
 [0.78395485 0.54614961 0.93359768 0.68092949]
 [0.41160493 0.57179346 0.34174536 0.28907917]
 [0.1851632  0.97139019 0.76766911 0.89160101]]


In [ ]:
# 5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [136]:
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)
add = a+b
sub = a-b
mul = a*b
print(a)
print(b)
print("Addition")
print(add)
print("Subtraction")
print(sub)
print("Multiplication")
print(mul)

[5 8 5 4 4]
[1 8 7 7 2]
Addition
[ 6 16 12 11  6]
Subtraction
[ 4  0 -2 -3  2]
Multiplication
[ 5 64 35 28  8]


In [ ]:
# 6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [77]:
a = np.random.random(7)
b = np.random.random(7)
scalar_product = np.dot(a,b)
print(a)
print(b)
print("Scalar product of vector a and vector b")
print(scalar_product)


[0.42795996 0.7450554  0.06577338 0.24903697 0.85543911 0.47119291
 0.34822434]
[0.7336854  0.68010387 0.51300616 0.80015622 0.70388398 0.52281331
 0.42398134]
Scalar product of vector a and vector b
2.0498301045714546


In [32]:
# 7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [138]:
a = np.random.randint(1,11, size=(2,2))
b = np.random.randint(1,11, size=(2,3))
scalar_product = np.dot(a,b)
print(a)
print(b)
print("Product of the two matrices:")
print(scalar_product)

[[10  7]
 [ 3  1]]
[[ 9  1  4]
 [ 9 10  5]]
Product of the two matrices:
[[153  80  75]
 [ 36  13  17]]


In [ ]:
# 8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [147]:
a = np.random.randint(1,11, size=(3,3))
a_inv = np.linalg.inv(a)
print(a)
print("Inverse of the 3x3 matrix:")
print(a_inv)

[[5 4 7]
 [2 7 8]
 [1 6 3]]
Inverse of the 3x3 matrix:
[[ 0.29347826 -0.32608696  0.18478261]
 [-0.02173913 -0.08695652  0.2826087 ]
 [-0.05434783  0.2826087  -0.29347826]]


In [ ]:
# 9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [142]:
a = np.random.random((4,4))
b = a.T
print("Original matrix:")
print(a)
print("Transformed matrix:")
print(b)

Original matrix:
[[0.58862256 0.64198072 0.05300179 0.85390104]
 [0.74914762 0.38951761 0.29054874 0.22359524]
 [0.54987623 0.63280963 0.42535905 0.73928077]
 [0.35132583 0.86451131 0.15745836 0.8799599 ]]
Transformed matrix:
[[0.58862256 0.74914762 0.54987623 0.35132583]
 [0.64198072 0.38951761 0.63280963 0.86451131]
 [0.05300179 0.29054874 0.42535905 0.15745836]
 [0.85390104 0.22359524 0.73928077 0.8799599 ]]


In [ ]:
# 10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [144]:
a = np.random.randint(1, 11, size=(3,4))
print("Matrix: a")
print(a)
b = np.random.randint(1, 11, size=(4,))
print("Vector: b")
print(b)
mul = np.dot(a, b)
print("Multiplying the matrix by the vector")
print(mul)


Matrix: a
[[ 6  5  7  3]
 [ 3 10  8  6]
 [ 2  5  9  6]]
Vector: b
[10  8  4  3]
Multiplying the matrix by the vector
[137 160 114]


In [ ]:
# 11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [123]:
a = np.random.rand(2, 3)
print("Matrix: a")
print(a)
b = np.random.rand(3)
print("Vector: b")
print(b)
scalar_product = np.dot(a,b)
print("Product of the matrix and vector")
print(scalar_product)

Matrix: a
[[0.63199728 0.9878396  0.85561572]
 [0.91174659 0.1240521  0.38718029]]
Vector: b
[0.13304674 0.06414508 0.86215901]
Product of the matrix and vector
[0.88512703 0.46307322]


In [ ]:
# 12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [99]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
mul = a*b
print(a)
print(b)
print("Multiplication of the two matrices:")
print(mul)

[[4 9]
 [2 9]]
[[ 7 10]
 [ 9  9]]
Multiplication of the two matrices:
[[28 90]
 [18 81]]


In [ ]:
# 13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [117]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
matrix_product = np.dot(a,b)
print(a)
print(b)
print("Products of the two matrices:")
print(matrix_product)

[[1 9]
 [8 9]]
[[ 3  8]
 [ 9 10]]
Products of the two matrices:
[[ 84  98]
 [105 154]]


In [ ]:
# 14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [148]:
a = np.random.randint(1, 101, size=(5, 5))
sum_element = np.sum(a)
print(a)
print('Sum of the matrix elements:', sum_element)


[[59 96 70 14 13]
 [97 49 38 90 48]
 [85 57 46 38 29]
 [87 78 28 75 57]
 [71 41 34 44 75]]
Sum of the matrix elements: 1419


In [ ]:
# 15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [134]:
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
difference = a - b
print("matrix: a")
print(a)
print("matrix: b")
print(b)
print("Difference:")
print(difference)

matrix: a
[[10  4  2  4]
 [ 6  9  1  3]
 [ 6 10  8 10]
 [ 9  5  1  5]]
matrix: b
[[ 6 10  8  5]
 [ 6 10  2  3]
 [ 3  5  6 10]
 [ 7  7  2  8]]
Difference:
[[ 4 -6 -6 -1]
 [ 0 -1 -1  0]
 [ 3  5  2  0]
 [ 2 -2 -1 -3]]


In [ ]:
# 16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [166]:
a = np.random.rand(3, 3)
print("Matrix: a")
print(a)
row_sum = np.sum(a, axis=1)
column_vector = row_sum.reshape(3, 1)
print('Row sum')
print(row_sum)
print("Column vector")
print(column_vector)


Matrix: a
[[0.69410995 0.97967223 0.9706235 ]
 [0.90670371 0.52085627 0.19882256]
 [0.90866113 0.22520458 0.93618484]]
Row sum
[2.64440568 1.62638253 2.07005054]
Column vector
[[2.64440568]
 [1.62638253]
 [2.07005054]]


In [ ]:
# 17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [180]:
a = np.random.randint(1, 11, size=(3, 4))
print("Matrix a")
print(a)
square_matrix = np.square(a)
print("Matrix of squares of these numbers")
print(square_matrix)

Matrix a
[[ 4  8  4  9]
 [ 6  4  4  6]
 [ 3  9  7 10]]
Matrix of squares of these numbers
[[ 16  64  16  81]
 [ 36  16  16  36]
 [  9  81  49 100]]


In [ ]:
# 18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [194]:
a = np.random.randint(1, 51, size=4)
sqrt_vector = np.sqrt(a)
print("Original vector")
print(a)
print("Vector with the square of these integers")
print(sqrt_vector)


Original vector
[29  3 18  6]
Vector with the square of these integers
[5.38516481 1.73205081 4.24264069 2.44948974]
