In [5]:
import numpy as np

In [ ]:
# 1. Замініть усі непарні числа в arr на -1 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr %2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
# 2. Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками

In [28]:
a = np.arange(10)
print(a)
b = a.reshape(2, -1)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
# 3. Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально

In [44]:
a = np.random.randint(1, 10, (2, 2))
print(a)
b = np.random.randint(1, 10, (2, 2))
print(b)
c = np.vstack((a, b))
print('Vertical stack a and b:')
print(c)


[[2 2]
 [8 8]]
[[9 5]
 [1 8]]
Vertical stack a and b:
[[2 2]
 [8 8]
 [9 5]
 [1 8]]


In [ ]:
# 4. Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy і наведений нижче масив введення Input:a = np.array([1,2,3])   Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [60]:
a = np.array([1, 2, 3])
output = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(output)


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [ ]:
# 5. Отримайте спільні елементи між a і b
# a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

In [67]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a, b)
print('Спільні елементи a і b')
print(c)

Спільні елементи a і b
[2 4]


In [ ]:
# 6. Отримайте позиції перших 5 максимальних значень у заданому масиві a
# np.random.seed(100) a = np.random.uniform(1,50, 20)

In [96]:
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
indices_of_top5 = np.argsort(a)[-5:][::-1]
print(indices_of_top5)

[15 10  3  7 18]


In [ ]:
# 7. Вилучіть усі значення NaN із одновимірного масиву
# а=np.array([1,2,3,np.nan,5,6,7,np.nan])

In [106]:
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
a_without_nan = a[~np.isnan(a)]
print(a_without_nan)

[1. 2. 3. 5. 6. 7.]


In [ ]:
# 8. Обчисліть евклідову відстань між двома масивами a і b.
# a = np.array([1,2,3,4,5]) b = np.array([4,5,6,7,8])

In [14]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
euclidean_distance = np.linalg.norm(a - b)
print('Euclidean distance:', euclidean_distance)

Euclidean distance: 6.708203932499369


In [ ]:
# 9. Знайдіть індекс 5-го повторення числа 1 у масиві x
# x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [31]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
indices_of_ones = np.where(x == 1)[0]
fifth_index = indices_of_ones[4]
print('Fifth index:', fifth_index)


Fifth index: 8


In [ ]:
# 10. Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. 
# Перше повторення має бути False.
# #Input 
# np.random.seed(100) 
# a = np.random.randint(0, 5, 10) 
# [0 0 3 0 2 4 2 2 2 2] 
# #Output [False True False True False False True True True True]

In [73]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print("Array a:", a)
# counts = np.bincount(a)  # використовується для підрахунку кількості появ кожного елемента
b = np.zeros_like(a, dtype=bool)
# print(b)
for number in np.unique(a):
    indices = np.where(a == number)[0]
    if len(indices) > 1:
        b[indices[1:]] = True
print("Output:", b)
# print(counts)

        

Array a: [0 0 3 0 2 4 2 2 2 2]
Output: [False  True False  True False False  True  True  True  True]
